# Generated by Django 6.0 on 2026-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=50, unique=True)),
                ('house_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PVR01', 'PVR01'), ('PVR02', 'PVR02'), ('PVR03', 'PVR03'), ('PVR04', 'PVR04')], max_length=10)),
                ('sub_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('House', 'House')], max_length=10, null=True)),
                ('lic_agent_name', models.CharField(max_length=100)),
                ('estimate_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=10)),
                ('client_mobile', models.CharField(max_length=15)),
                ('file_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
